// In this file you can specify the trial data for your experiment


const trial_practice = {
    key_press_choice: [
        {
          question: "Are this figures the same or different?",
          picture: "images/1_50_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "50",
          picture_number: "1",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/1_50_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "50",
          picture_number: "1",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/1_150_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "150",
          picture_number: "1",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/1_150_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "150",
          picture_number: "1",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/2_50_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "50",
          picture_number: "2",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/2_50_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "50",
          picture_number: "2",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/2_150_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "150",
          picture_number: "2",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/2_150_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "150",
          picture_number: "2",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/3_50_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "50",
          picture_number: "3",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/3_50_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "50",
          picture_number: "3",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/3_150_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "150",
          picture_number: "3",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/3_150_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "150",
          picture_number: "3",
          picture_object: "same"
        },
      ]
  };
const trial_main = {
      key_press_choice: [
        {
          question: "Are this figures the same or different?",
          picture: "images/4_50_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "50",
          picture_number: "4",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/4_50_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "50",
          picture_number: "4",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/4_150_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "150",
          picture_number: "4",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/4_150_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "150",
          picture_number: "4",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/5_50_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "50",
          picture_number: "5",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/5_50_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "50",
          picture_number: "5",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/5_150_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "150",
          picture_number: "5",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/5_150_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "150",
          picture_number: "5",
          picture_object: "same"
        },{
          question: "Are this figures the same or different?",
          picture: "images/6_50_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "50",
          picture_number: "6",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/6_50_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "50",
          picture_number: "6",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/6_150_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "150",
          picture_number: "6",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/6_150_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "150",
          picture_number: "6",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/7_50_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "50",
          picture_number: "7",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/7_50_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "50",
          picture_number: "7",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/7_150_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "150",
          picture_number: "7",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/7_150_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "150",
          picture_number: "7",
          picture_object: "same"
        },{
          question: "Are this figures the same or different?",
          picture: "images/8_50_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "50",
          picture_number: "8",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/8_50_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "50",
          picture_number: "8",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/8_150_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "150",
          picture_number: "8",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/8_150_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "150",
          picture_number: "8",
          picture_object: "same"
        },{
          question: "Are this figures the same or different?",
          picture: "images/9_50_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "50",
          picture_number: "9",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/9_50_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "50",
          picture_number: "9",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/9_150_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "150",
          picture_number: "9",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/9_150_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "150",
          picture_number: "9",
          picture_object: "same"
        },{
          question: "Are this figures the same or different?",
          picture: "images/10_50_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "50",
          picture_number: "19",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/10_50_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "50",
          picture_number: "10",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/10_150_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "150",
          picture_number: "10",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/10_150_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "150",
          picture_number: "10",
          picture_object: "same"
        },{
          question: "Are this figures the same or different?",
          picture: "images/11_50_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "50",
          picture_number: "11",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/11_50_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "50",
          picture_number: "11",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/11_150_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "150",
          picture_number: "11",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/11_150_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "150",
          picture_number: "11",
          picture_object: "same"
        },{
          question: "Are this figures the same or different?",
          picture: "images/12_50_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "50",
          picture_number: "12",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/12_50_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "50",
          picture_number: "12",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/12_150_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "150",
          picture_number: "12",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/12_150_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "150",
          picture_number: "12",
          picture_object: "same"
        },{
          question: "Are this figures the same or different?",
          picture: "images/13_50_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "50",
          picture_number: "13",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/13_50_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "50",
          picture_number: "13",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/13_150_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "150",
          picture_number: "13",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/13_150_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "150",
          picture_number: "13",
          picture_object: "same"
        },{
          question: "Are this figures the same or different?",
          picture: "images/14_50_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "50",
          picture_number: "14",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/14_50_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "50",
          picture_number: "14",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/14_150_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "150",
          picture_number: "14",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/14_150_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "150",
          picture_number: "14",
          picture_object: "same"
        },{
          question: "Are this figures the same or different?",
          picture: "images/15_50_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "50",
          picture_number: "15",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/15_50_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "50",
          picture_number: "15",
          picture_object: "same"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/15_150_different.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'different',
          degree: "150",
          picture_number: "15",
          picture_object: "different"
        },
        {
          question: "Are this figures the same or different?",
          picture: "images/15_150_same.jpg",
          key1: 's',
          key2: 'd',
          s: 'same',
          d: 'different',
          correct: 'same',
          degree: "150",
          picture_number: "1",
          picture_object: "same"
        },
    ]
};
